version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres_admin:
    image: dpage/pgadmin4:6.12
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  api:
    env_file:
      - .env
    container_name: api
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "yarn run start:dev"
    depends_on:
      - postgres
      - redis
    ports:
      - ${PORT}:${PORT}
      - '9229:9229'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mailhog:
    image: mailhog/mailhog
    restart: always
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  redis:
    container_name: redis
    image: redis:6.0.9-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'

volumes:
  redis:
    driver: local
  postgres:
    driver: local

networks:
  postgres:
    driver: bridge
